# version: '3.8'

services:
  # Spring Boot service
  spring-boot-app:
    image: spring-boot-app
    build:
      context: .  # Path to your project directory
      dockerfile: Dockerfile  # Dockerfile for the Spring Boot app
    ports:
      - "8081:8081"  # Map Spring Boot port to host
    depends_on:
      mysql-db:
        condition: service_healthy  # Ensure MySQL service is healthy before starting Spring Boot
    environment:
      SPRING_APPLICATION_NAME: backend
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/codenest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    networks:
      - webapp-network
    command: ["./wait-for-it.sh", "mysql-db:3306", "--timeout=60", "--", "java", "-jar", "app.jar"]

  # MySQL service
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codenest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf  # Mount the custom my.cnf file here
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  webapp-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local